# Generated by Django 4.2.7 on 2023-11-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="media/default-image.jpg", upload_to="product-images/"
            ),
        ),
    ]
